src/main/java/org/cinema/managedbeans/DetalhesDoFilmeBean.java
package org.cinema.managedbeans;

import java.io.Serializable;

import javax.faces.view.ViewScoped;
import javax.inject.Inject;
import javax.inject.Named;

import org.cinema.entidades.jpa.Filme;
import org.cinema.utils.MessagesHelper;
import org.cinema.utils.UrlDeImagensHelper;
import org.cinema.services.FilmeService;

// bean da pagina de detalhes do filme

@Named
@ViewScoped
public class DetalhesDoFilmeBean implements Serializable {

    private static final long serialVersionUID = -7541082218215581325L;

    @Inject
    private transient MessagesHelper messagesHelper;

    @Inject
    private transient FilmeService service;

    @Inject
    private transient UrlDeImagensHelper urlDeImagensHelper;

    private Filme filme;
    private Long id;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public void carregar() {
        filme = service.buscar(id);
    }

    public Filme getFilme() {
        return filme;
    }

    public void setFilme(Filme filme) {
        this.filme = filme;
    }

    public String getUrlDaImagemDoFilme() {
        if (filme == null || filme.getId() == null) {
            return "";
        }

        return urlDeImagensHelper
                .getUrlDaImagemDoFilme(filme.getId(), "cartaz");
    }

}

src/main/java/org/cinema/managedbeans/FilmesBean.java
package org.cinema.managedbeans;

import java.io.IOException;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.UUID;
import java.util.stream.Collectors;

import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;
import javax.faces.model.SelectItem;
import javax.faces.view.ViewScoped;
import javax.inject.Inject;
import javax.inject.Named;
import javax.transaction.Transactional;

import org.cinema.entidades.jpa.Filme;
import org.cinema.entidades.jpa.Filme.Censura;
import org.cinema.entidades.sistema.Imagem;
import org.cinema.utils.MessagesHelper;
import org.cinema.infra.imagens.RepositorioDeImagensDeFilmes;
import org.cinema.infra.imagens.RepositorioDeImagensTemporarias;
import org.cinema.utils.UrlDeImagensHelper;
import org.cinema.services.FilmeService;
import org.primefaces.event.FileUploadEvent;
import org.primefaces.model.UploadedFile;

@Named
@ViewScoped
public class FilmesBean implements Serializable {

    private static final long serialVersionUID = -7541082218215581325L;

    @Inject
    private transient MessagesHelper messagesHelper;
    
    @Inject
    private transient FilmeService service;
    
    @Inject
    private transient RepositorioDeImagensTemporarias repoDeImagensTemporarias;
    
    @Inject
    private transient RepositorioDeImagensDeFilmes repoDeImagensDeFilmes;
    
    @Inject
    private transient UrlDeImagensHelper urlDeImagensHelper;

    private Filme filme = new Filme();
    private boolean editar = false;

    private UUID idDaImagemTemporaria;

    
    public void limpar() {
        this.filme = new Filme();
        setEditar(false);
        limparImagemTemporaria();
    }

    // carrega um filme para ediçao
    public void carregar(Long id) {
        filme = service.buscar(id);
        setEditar(true);
        limparImagemTemporaria();
    }

    // o metodo do bean e executado em uma transacao, necessario nos beans gerenciados pelo CDI
    @Transactional
    public void salvar() throws IOException {
        
        // se a imagem nao foi selecionada envia uma mensagem de erro
        if (idDaImagemTemporaria == null) {
            FacesContext.getCurrentInstance().validationFailed();
            messagesHelper.addMessage(new FacesMessage(FacesMessage.SEVERITY_WARN, "Por favor, selecione uma imagem de cartaz", ""));
            
            return;
        }
        
        // salva o filme
        service.persist(filme);
        
        // salva a imagem
        Imagem imagem = repoDeImagensTemporarias.obterImagemCom(idDaImagemTemporaria);
        repoDeImagensDeFilmes.salvar(imagem, filme.getId(), "cartaz");

        // envia uma mensagem de sucesso
        messagesHelper.addMessage(new FacesMessage("Filme cadastrado com sucesso!"));
    }

    // o metodo do bean e executado em uma transacao, necessario nos beans gerenciados pelo CDI
    @Transactional
    public void atualizar() throws IOException {
        // atualiza o filme
        service.merge(filme);
        
        // atualiza a imagem somente se ela foi enviada
        if (idDaImagemTemporaria != null) {
            Imagem imagem = repoDeImagensTemporarias.obterImagemCom(idDaImagemTemporaria);
            repoDeImagensDeFilmes.salvar(imagem, filme.getId(), "cartaz");
        }
        
        // envia uma mensagem de sucesso
        messagesHelper.addMessage(new FacesMessage("Filme atualizado com sucesso!"));
    }

    // o metodo do bean e executado em uma transacao, necessario nos beans gerenciados pelo CDI
    @Transactional
    public void remover(Long id) {
        filme = service.buscar(id); // busca o filme
        service.remover(filme); // remove o filme
        
        // envia uma mensage de sucesso
        messagesHelper.addMessage(new FacesMessage("Filme removido com sucesso!"));
    }

    public List<Filme> getAll() {
        return service.list();
    }

    public Filme getFilme() {
        return filme;
    }

    public void setFilme(Filme filme) {
        this.filme = filme;
    }

    public boolean isEditar() {
        return editar;
    }

    public void setEditar(boolean editar) {
        this.editar = editar;
    }

    // manipula o upload de imagems
    public void handleFileUpload(FileUploadEvent event) throws IOException {
        
        // obtenho a imagem enviada
        UploadedFile uploadedFile = event.getFile();
        
        // crio uma instance de Imagem
        Imagem imagem = new Imagem(uploadedFile);
        
        // limpo a imagem temporaria anterior
        limparImagemTemporaria();
        
        // salvo a imagem temporaria e atribuo o id para a variavel do bean
        idDaImagemTemporaria = repoDeImagensTemporarias.salvar(imagem);
    }

    public UUID getIdImagemTemporaria() {
        return idDaImagemTemporaria;
    }

    // serve para limpar a imagem temporaria atual
    private void limparImagemTemporaria() {
        if (idDaImagemTemporaria != null) {
            repoDeImagensTemporarias.removerImagemCom(idDaImagemTemporaria);
            idDaImagemTemporaria = null;
        }
    }

    // retorna o endereco da imagem para ser visualizada na pagina
    public String getUrlDaImagemTemporaria() {

        if (idDaImagemTemporaria != null) {
            return urlDeImagensHelper.getUrlDeImagemTemporaria(idDaImagemTemporaria.toString());
        }

        if (editar == true) {
            return getUrlDaImagemDoFilme();
        }

        // imagem default
        return "/resources/img/default-cartaz.png";
    }

    public String getUrlDaImagemDoFilme() {
        if (filme == null || filme.getId() == null) {
            return "";
        }

        return urlDeImagensHelper
                .getUrlDaImagemDoFilme(filme.getId(), "cartaz");
    }

    public String getTituloDoModalDoFormulario() {
        if (editar) {
            return "Editar filme";
        }

        return "Cadastrar filme";
    }

    public SelectItem[] getCensuras() {

        List<SelectItem> itens = new ArrayList<>();

        for (Censura censura : Censura.values()) {
            itens.add(new SelectItem(censura, censura.toString()));
        }

        return itens.toArray(new SelectItem[itens.size()]);
    }

    public List<String> completarGenero(String query) {

        List<String> generos = Arrays.asList("Ação", "Animação", "Aventura",
                "Comédia", "Documentário", "Drama", "Família", "Fantasia",
                "Ficção científica", "Filme noir", "Guerra", "Musical",
                "Policial", "Romance", "Suspense", "Terror", "Thriller",
                "Western");

        List<String> generosFiltrados = generos.stream().filter((genero) -> {
            return genero.toLowerCase().contains(query.toLowerCase());
        }).collect(Collectors.toList());

        generosFiltrados.add(0, query);

        return generosFiltrados;
    }
}

src/main/webapp/admin/detalhesDoFilme.xhtml
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:p="http://primefaces.org/ui"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:ui="http://java.sun.com/jsf/facelets">

    <f:metadata>
        <f:viewParam id="id" name="id" value="#{detalhesDoFilmeBean.id}" />
        <f:viewAction action="#{detalhesDoFilmeBean.carregar()}" />
    </f:metadata>

    <ui:composition template="/template.xhtml">

        <ui:define name="conteudo">

            <div class="ui-grid ui-grid-responsive">
                <div class="ui-grid-row">
                    <div class="ui-grid-col-2">
                        <p:panel header="Imagem de cartaz">
                            <p:graphicImage width="100%"
                                            url="#{detalhesDoFilmeBean.urlDaImagemDoFilme}" cache="false" />
                        </p:panel>
                    </div>
                    <div class="ui-grid-col-10" style="padding-left: 20px;">

                        <p:panel>
                            <h1>
                                <h:outputText value="#{detalhesDoFilmeBean.filme.titulo}" />
                            </h1>
                            <hr />
                            <ul
                                style="list-style: none; margin: 0; padding: 0; line-height: 1.5;">
                                <li><b>Gênero:</b> <ui:repeat var="genero"
                                                              value="#{detalhesDoFilmeBean.filme.generos}">
                                        <span
                                            style="font-size: 0.8em; background-color: #c00; color: #fff; padding: 1px; border-radius: 5px;">#{genero}</span>
                                    </ui:repeat></li>
                                <li><b>Ano:</b> #{detalhesDoFilmeBean.filme.ano}</li>
                                <li><b>Censura:</b>
                                    #{detalhesDoFilmeBean.filme.censura.toString()}</li>
                                <li><b>Diretor:</b> #{detalhesDoFilmeBean.filme.diretor}</li>
                                <li><b>Duração:</b>
                                    #{detalhesDoFilmeBean.filme.duracaoEmMinutos}min</li>
                                <li><b>Resumo:</b> #{detalhesDoFilmeBean.filme.resumo}</li>
                            </ul>
                        </p:panel>

                        <p:panel style="margin-top: 20px;">
                            <h2>Sessões</h2>
                            <hr />

                            <h:form>
                                <p:commandButton value="Cadastrar sessão"
                                                 action="#{cadastroDeSessaoBean.limpar()}"
                                                 update="formSessao formConfiguracaoDiaria formHorario"
                                                 onclick="PF('painelCadastroDeSessao').show();$('.ui-layout-center > div').scrollTop(400);" />
                            </h:form>

                            <p:dataTable value="#{detalhesDoFilmeBean.filme.sessoes}"
                                         var="sessao" id="sessoesTable">

                                <p:column headerText="Vídeo" width="30">
                                    <h:outputText value="#{sessao.video.toString()}" />
                                </p:column>

                                <p:column headerText="Áudio" width="200">
                                    <h:outputText value="#{sessao.audio.toString()}" />
                                </p:column>

                                <p:column headerText="Configurações Diárias">
                                    <ui:repeat var="configuracaoDiaria"
                                               value="#{sessao.configuracoesDiarias}">
                                        <h:panelGrid columns="1">
                                            <h:outputText value="#{configuracaoDiaria}" />
                                        </h:panelGrid>
                                    </ui:repeat>
                                </p:column>

                                <p:column width="100">
                                    <h:form>
                                        <p:commandButton value="Excluir"
                                                         action="#{cadastroDeSessaoBean.remover(sessao.id)}"
                                                         oncomplete="location.reload();"
                                                         update="sessoesTable" />
                                    </h:form>
                                </p:column>

                            </p:dataTable>

                            <p:panel header="Cadastro de sessão" style="margin-top:20px;"
                                     visible="false" closable="true"
                                     widgetVar="painelCadastroDeSessao">

                                <h:form id="formSessao">

                                    <h:panelGrid columns="2" cellpadding="5">
                                        <h:outputLabel value="Vídeo" />
                                        <p:selectOneRadio value="#{cadastroDeSessaoBean.sessao.video}">
                                            <f:selectItem itemLabel="2D" itemValue="_2D" />
                                            <f:selectItem itemLabel="3D" itemValue="_3D" />
                                        </p:selectOneRadio>
                                    </h:panelGrid>

                                    <h:panelGrid columns="2" cellpadding="5">

                                        <h:outputLabel value="Áudio" />
                                        <p:selectOneRadio value="#{cadastroDeSessaoBean.sessao.audio}">
                                            <f:selectItem itemLabel="Dublado" itemValue="DUBLADO" />
                                            <f:selectItem itemLabel="Legendado" itemValue="LEGENDADO" />
                                            <f:selectItem itemLabel="Nacional" itemValue="NACIONAL" />
                                        </p:selectOneRadio>

                                    </h:panelGrid>


                                    <p:commandButton action="#{cadastroDeSessaoBean.salvar}"
                                                     oncomplete="PF('painelCadastroDeSessao').close();"
                                                     value="Adicionar sessão" update="sessoesTable" />

                                </h:form>


                                <p:panel>
                                    <h4>Adicionar configuração diária</h4>
                                    <h:form id="formConfiguracaoDiaria">
                                        <h:panelGrid columns="6" cellpadding="8">

                                            <h:outputText value="Dia da semana:" />
                                            <p:selectOneMenu style="width: 100px"
                                                             value="#{cadastroDeSessaoBean.configuracaoDiaria.diaDaSemana}">

                                                <f:selectItems value="#{cadastroDeSessaoBean.diasDaSemana()}" />

                                            </p:selectOneMenu>

                                            <p:commandButton value="Adicionar configuração diária"
                                                             update="formConfiguracaoDiaria configuracoesDiariasTable formHorario"
                                                             action="#{cadastroDeSessaoBean.resetColetorDeConfiguracaoDiaria}">

                                                <p:collector
                                                    value="#{cadastroDeSessaoBean.configuracaoDiaria}"
                                                    addTo="#{cadastroDeSessaoBean.sessao.configuracoesDiarias}"
                                                    unique="false" />

                                            </p:commandButton>

                                        </h:panelGrid>
                                    </h:form>


                                    <!-- 		panel de horários -->

                                    <h5>Adicionar Horários</h5>

                                    <h:form id="formHorario">
                                        <h:panelGrid columns="5" cellpadding="5">

                                            <p:outputLabel for="horario" value="Horário" />
                                            <p:inputMask id="horario"
                                                         value="#{cadastroDeSessaoBean.horario.horario}" mask="99:99">

                                            </p:inputMask>

                                            <p:outputLabel value="Sala" />
                                            <p:selectOneMenu value="#{cadastroDeSessaoBean.horario.sala}"
                                                             style="width:125px">
                                                <f:selectItem itemLabel="" itemValue="" />
                                                <f:selectItem itemLabel="Sala 1" itemValue="Sala 1" />
                                                <f:selectItem itemLabel="Sala 2" itemValue="Sala 2" />
                                                <f:selectItem itemLabel="Sala 3" itemValue="Sala 3" />
                                                <f:selectItem itemLabel="Sala 4" itemValue="Sala 4" />

                                            </p:selectOneMenu>

                                            <p:commandButton value="Adicionar"
                                                             update="formHorario horariosTable"
                                                             action="#{cadastroDeSessaoBean.resetColetorDeHorarios}">

                                                <p:collector value="#{cadastroDeSessaoBean.horario}"
                                                             addTo="#{cadastroDeSessaoBean.configuracaoDiaria.horarios}"
                                                             unique="false"/>

                                            </p:commandButton>

                                        </h:panelGrid>
                                    </h:form>

                                    <!-- 	tabela de horários -->
                                    <p:dataTable
                                        value="#{cadastroDeSessaoBean.configuracaoDiaria.horarios}"
                                        var="horario" id="horariosTable">

                                        <p:column headerText="Horários">
                                            <h:outputText value="#{horario}" />
                                        </p:column>

                                    </p:dataTable>

                                </p:panel>

                                <!-- tabela de configurações diárias -->
                                <p:dataTable id="configuracoesDiariasTable"
                                             value="#{cadastroDeSessaoBean.sessao.configuracoesDiarias}"
                                             var="configuracaoDiaria" style="margin-top:15px">

                                    <p:column headerText="Configurações diárias">
                                        <h:outputText value="#{configuracaoDiaria}" />
                                    </p:column>

                                </p:dataTable>

                            </p:panel>

                        </p:panel>

                    </div>
                </div>
            </div>


        </ui:define>
    </ui:composition>
</html>

src/main/webapp/admin/gerenciarFilmes.xhtml
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:p="http://primefaces.org/ui"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets">

<ui:composition template="/template.xhtml">

	<ui:define name="conteudo">

		<p:panel header="Gerenciar Filmes">
			<h:form>
				<p:commandButton value="Cadastrar filme" id="botao-cadastrar"
					update="modal-form" action="#{filmesBean.limpar()}"
					oncomplete="PF('modal-form').show();" icon="ui-icon-circle-plus" />
			</h:form>

			<p:dataTable value="#{filmesBean.all}" var="filme"
				emptyMessage="Não existem registros." id="tabela" paginator="true"
				rows="5">

				<p:column width="50">
					<h:form>
						<p:button outcome="detalhesDoFilme" icon="ui-icon-zoomin">
							<f:param name="id" value="#{filme.id}" />
						</p:button>
					</h:form>
				</p:column>

				<p:column headerText="Título">
					<h:outputText value="#{filme.titulo}" />
				</p:column>

				<p:column headerText="Ano">
					<h:outputText value="#{filme.ano}" />
				</p:column>

				<p:column>
					<h:form>
						<p:commandButton value="Editar"
							action="#{filmesBean.carregar(filme.id)}"
							oncomplete="PF('modal-form').show();" update="modal-form" />

						<p:commandButton value="Excluir"
							action="#{filmesBean.remover(filme.id)}" update="tabela" />
					</h:form>
				</p:column>
			</p:dataTable>
		</p:panel>

	</ui:define>

	<ui:define name="modal">

		<!-- 		Modal do formulário do filme -->
		<p:dialog header="#{filmesBean.tituloDoModalDoFormulario}"
			widgetVar="modal-form" id="modal-form" closeOnEscape="true"
			maximizable="true" modal="true" width="80%" showEffect="fade">

			<h:form id="formulario" enctype="multipart/form-data"
				prependId="false">

				<div class="ui-grid ui-grid-responsive">
					<div class="ui-grid-row">
						<div class="ui-grid-col-3">

							<p:panel style="text-align:center;" header="Imagem de cartaz">
								<p:graphicImage id="imagemPreview"
									url="#{filmesBean.urlDaImagemTemporaria}" cache="false"
									width="80%" />

								<p:fileUpload label="Escolher" skinSimple="true"
									fileUploadListener="#{filmesBean.handleFileUpload}"
									mode="advanced" auto="true" sizeLimit="40000000"
									allowTypes="/(\.|\/)(jpe?g|png)$/" update="imagemPreview">
								</p:fileUpload>

							</p:panel>
						</div>
						<div class="ui-grid-col-9">

							<p:panel header="Dados do filme" style="margin-left:20px;">

								<div class="ui-grid-row">
									<div class="ui-grid-col-6">
										<h:panelGrid columns="2" cellpadding="10">
											<h:outputFormat value="Título" />
											<p:inputText value="#{filmesBean.filme.titulo}" />

											<h:outputFormat value="Ano" />
											<p:slider display="ano" minValue="1990" maxValue="2050"
												for="ano">
												<p:inputText value="#{filmesBean.filme.ano}" id="ano" />
											</p:slider>

											<h:outputFormat value="Duração (Minutos)" />
											<p:slider display="duracao" minValue="1" maxValue="500"
												for="duracao">
												<p:inputText value="#{filmesBean.filme.duracaoEmMinutos}"
													id="duracao" />
											</p:slider>

											<h:outputFormat value="Diretor" />
											<p:inputText value="#{filmesBean.filme.diretor}" />



											<p:commandButton value="Cadastrar"
												action="#{filmesBean.salvar}" update="tabela,formulario"
												oncomplete="hideModalOnSuccess(xhr, status, args, 'modal-form');"
												rendered="#{!filmesBean.editar}" icon="ui-icon-disk" />

											<p:commandButton value="Atualizar"
												action="#{filmesBean.atualizar}" update="tabela,formulario"
												oncomplete="hideModalOnSuccess(xhr, status, args, 'modal-form');"
												rendered="#{filmesBean.editar}" />

											<p:button value="Cancelar" onclick="PF('modal-form').hide();"
												icon="ui-icon-closethick" />

										</h:panelGrid>
									</div>
									<div class="ui-grid-col-6">
										<h:panelGrid columns="2" cellpadding="10">

											<h:outputText value="Gênero" />
											<p:autoComplete value="#{filmesBean.filme.generos}"
												completeMethod="#{filmesBean.completarGenero}"
												multiple="true" />

											<h:outputText value="Censura" />
											<p:selectOneMenu value="#{filmesBean.filme.censura}">
												<f:selectItems value="#{filmesBean.censuras}" var="censura"
													itemLabel="#{censura}" itemValue="#{censura}" />
											</p:selectOneMenu>

											<h:outputText value="Resumo" />
											<p:inputTextarea value="#{filmesBean.filme.resumo}"
												style="max-height:250px;" />

										</h:panelGrid>
									</div>
								</div>
							</p:panel>
						</div>
					</div>

				</div>
			</h:form>

		</p:dialog>
	</ui:define>
</ui:composition>
</html>